Render: false
Language: zh
Show_Prior: false
Training:
  agent_name: mappo
  episodes: 3
  max_steps: 600
  batch_size: 32
  lr: 0.0003
  seed: -1
  train: true
  save_threshold: -100
  num_workers: 1
  ckpt_path: ''
Environment:
  init_width: 2
  init_height: 2
  boundary: [[1.0, 3.0], [5.0, 3.0], [5.0, 2.0],[11.0, 2.0],[11.0, 3.0],[16.0, 3.0], [16.0, 6.0], [14.0, 6.0], [14.0, 13.0], [11.0, 13.0], [11.0, 10.0], [10.0, 10.0], [10.0, 9.0], [5.0, 9.0], [5.0, 7.0], [1.0, 7.0]]
  door_positions: [[12.0, 13.0], [13.0, 13.0]]
  door_direction: 水平
  prior: [[3.6, 4.4], [8.6, 8.4], [7.1, 7.9], [2.0, 2.0], [12.0, 2.0], [12.0, 10.0], [5.0, 5.0]]
  prior_random: false
  prior_limit_area: []
  prior_interval: 3
  room_type: [卧室, 卧室, 卧室, 卧室, 阳台, 浴室, 浴室, 厨房]
  move_value: 0.05
  reward_method: extra
  Reward_Extra_Weight:
    邻接关系奖励: 0.0
    噪声干扰度奖励: 0.0
    隐私保护奖励: 1.0
    南向采光奖励: 0.0
    最短路径奖励: 0.0
  Reward_Base_Weight:
    面积奖励: 1.0
    长宽比奖励: 1.0
    贴边奖励: 1.0
    房间与房间之间的边界贴合奖励: 1.0
    角落占领奖励: 1.0
    外门遮挡惩罚: 1.0
    先验知识布局奖励: 1.0
    房间嵌套惩罚: 1.0
Room:
  MinAreas:
    卧室: 9
    厨房: 4
    浴室: 4
    阳台: 3
    客厅: 4
  UseAreasRatio: false
  MaxAreasRatio:
    卧室: 0.4
    厨房: 0.25
    浴室: 0.25
    阳台: 0.25
  MaxAreasValue:
    卧室: 16
    厨房: 12
    浴室: 12
    阳台: 12
  ASPECT_RATIO_RANGES:
    卧室: [1.0, 1.6]
    厨房: [1.0, 1.8]
    浴室: [1.0, 1.6]
    阳台: [1.0, 2.8]
  NOISE_WEIGHTS:
    客厅: 5.5
    卧室: 5.5
    厨房: 2.5
    浴室: 0.0
    阳台: 1.5
  NESTING_WEIGHTS:
    客厅: 0.25
    卧室: 0.0
    厨房: 0.15
    浴室: 0.1
    阳台: 0.3
  NESTING_PRIORITY:
    客厅: 1
    卧室: 5
    厨房: 2
    浴室: 4
    阳台: 3
